# Generated by Django 6.0.2 on 2026-02-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(help_text="Nom de l'université", max_length=200)),
                ('degree', models.CharField(help_text='Nom de la formation', max_length=200)),
                ('start_year', models.IntegerField(help_text='Année de début')),
                ('graduation_year', models.IntegerField(blank=True, help_text="Année d'obtention (laisser vide si en cours)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Intitulé du poste', max_length=200)),
                ('company', models.CharField(help_text="Nom de l'entreprise", max_length=200)),
                ('location', models.CharField(help_text='Ville, Pays', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Laisser vide si poste actuel', null=True)),
                ('description', models.TextField(help_text='Description des responsabilités')),
                ('is_current', models.BooleanField(default=False, help_text='Poste actuel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=300)),
                ('github_link', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la technologie', max_length=100)),
                ('category', models.CharField(choices=[('languages', 'Langages'), ('ai_ml', 'Intelligence Artificielle & Machine Learning'), ('web_frameworks', 'Frameworks Web'), ('databases', 'Bases de Données'), ('tools_devops', 'Outils & DevOps')], max_length=50)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage (0 = premier)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
