# Generated by Django 6.0.2 on 2026-02-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('student_job', 'Job Étudiant'), ('internship', 'Stage'), ('permanent', 'CDI'), ('temporary', 'CDD'), ('freelance', 'Freelance')], default='student_job', help_text="Type d'expérience", max_length=50),
        ),
    ]
