# Generated by Django 6.0.2 on 2026-02-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_experience_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('languages', 'Langages'), ('methode', 'Méthode'), ('ai_ml', 'Intelligence Artificielle & Machine Learning'), ('web_frameworks', 'Frameworks Web'), ('databases', 'Bases de Données'), ('tools_devops', 'Outils & DevOps')], max_length=50),
        ),
    ]
