# Generated by Django 6.0.2 on 2026-02-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('languages', 'Langages'), ('langues', 'Langues'), ('methodes', 'Méthodes'), ('ai_ml', 'Intelligence Artificielle & Machine Learning'), ('web_frameworks', 'Frameworks Web'), ('databases', 'Bases de Données'), ('tools_devops', 'Outils & DevOps')], max_length=50),
        ),
    ]
