# Generated by Django 6.0.2 on 2026-06-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_personalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='bio',
            field=models.TextField(blank=True, help_text="Description affichée sur la page d'accueil"),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Ex: Ingénieur IA & Développeur', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, help_text='Lien vers la démo en ligne', null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True),
        ),
    ]
