# Generated by Django 6.0.2 on 2026-06-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_personalinfo_bio_personalinfo_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('languages', 'Langages'), ('langues', 'Langues'), ('methodes', 'Méthodes'), ('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('web_frameworks', 'Frameworks Web'), ('databases', 'Bases de Données'), ('tools_mlops', 'Outils & MLOps')], max_length=50),
        ),
    ]
